obj-y += sched hw resources faults
obj-y += boot.o init.o seg.o idt.o asm.o mem.o ptable.o timer.o \
	platform.o interrupt.o syscalls.o usercopy.o fault.o \
	utrampoline.o signal.o time.o memcpy.o memset.o server.o

obj-$(CONFIG_SMP) += smp.o smp_int.o apboot.o


