obj-y += sched hw resources faults
obj-y += boot.o init.o seg.o irq.o mem.o ptable.o timer.o \
	platform.o interrupt.o syscalls.o usercopy.o fault.o \
	utrampoline.o signal.o time.o memcpy.o memset.o ptrace.o server.o \
	mmpool_conf.o acpi.o apic.o ioapic.o context.o i8254.o i8259.o

obj-$(CONFIG_SMP) += smp.o smp_int.o apboot.o


