LIBEZA_OBJS=eza/generic_api/main.o \
	eza/generic_api/kconsole.o \
	eza/generic_api/vga.o \
	eza/generic_api/syscall.o \
	eza/generic_api/interrupt.o \
	eza/generic_api/timer.o \
	eza/generic_api/scheduler.o \
	eza/generic_api/time.o \
	eza/generic_api/init.o \
	eza/generic_api/hardware.o \
	eza/generic_api/swks.o \
	eza/generic_api/kstack.o \
	eza/generic_api/task.o \
	eza/generic_api/idletask.o \
	eza/generic_api/panic.o \
	eza/generic_api/process.o \
	eza/generic_api/schedulers/sched_default.o \
	eza/generic_api/security.o
