obj-y += mm sched hw resources faults
obj-y += boot.o asm.o cpu.o bios.o timer.o platform.o interrupt.o idt.o \
	syscalls.o usercopy.o fault.o pmm.o e820map.o signal.o utrampoline.o
obj-$(CONFIG_SMP) += smp.o smp_int.o smpap.o


